# Generated by Django 4.2 on 2023-04-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='direccion',
            new_name='contraseña',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefono',
        ),
    ]
