# Generated by Django 4.2 on 2023-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_rename_direccion_clientes_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
